name: Manual PROD deploy
on:
    workflow_dispatch:
        inputs:
            update_simbioz:
                description: "Update SIMBIOZ sources"
                default: false
                required: true
                type: boolean
            base_update:
                description: "Full update (BASE module)"
                default: false
                required: false
                type: boolean

jobs:
    DEPLOY:
        uses: BorovlevAS/ci_cd_workflows/.github/workflows/manual_prod_deploy.yml@main
        with:
            update_simbioz: ${{ inputs.update_simbioz }}
            base_update: ${{ inputs.base_update }}
            SERVER_ADDR: ${{vars.PROD_SERV_ADDR}}
            SERVER_USER: ${{vars.PROD_SERV_USER}}
            SERVER_PORT: ${{vars.PROD_SERV_PORT}}
            MAIN_PATH: ${{vars.PROD_MAIN_PATH}}
            CUSTOM_PATH: ${{vars.PROD_CUSTOM_PATH}}
            ODOO_SERVICE: ${{vars.PROD_ODOO_SERVICE}}
            ODOO_USER: ${{vars.PROD_ODOO_USER}}
            ODOO_URI: ${{vars.PROD_ODOO_ADDR}}
            ODOO_DB: ${{vars.PROD_DB_NAME}}
        secrets:
            SSH_KEY: ${{secrets.PROD_SSH_KEY}}
            ODOO_PASSWORD: ${{secrets.PROD_ODOO_ADMIN_PWD}}
