name: Manual STAGE deploy
on:
    workflow_dispatch:
        inputs:
            update_simbioz:
                description: "Update SIMBIOZ sources"
                default: false
                required: false
                type: boolean
            base_update:
                description: "Full update (BASE module)"
                default: false
                required: false
                type: boolean
            exclusive_update:
                description: "Turn off database during update"
                required: false
                type: boolean
                default: false
            show_log:
                description: "Show detailed log during update"
                required: false
                type: boolean
                default: false
            ODOO_DB:
                required: false
                type: string

concurrency:
    group: ci-stage-${{ github.ref }}
    cancel-in-progress: false

jobs:
    DEPLOY:
        runs-on:
            group: preprod-runners
        steps:
            - name: Deploy
              uses: biko-solutions/cicd_workflows/.github/actions/self-hosted-run/simbioz-struct/deploy@main
              with:
                  base_update: ${{ inputs.base_update }}
                  update_simbioz: ${{ inputs.update_simbioz }}
                  exclusive_update: ${{ inputs.exclusive_update }}
                  show_log: ${{ inputs.show_log }}
                  MAIN_PATH: ${{vars.STAGE_MAIN_PATH}}
                  CUSTOM_PATH: ${{vars.STAGE_CUSTOM_PATH}}
                  ODOO_SERVICE: ${{vars.STAGE_ODOO_SERVICE}}
                  SERVER_USER: ${{vars.STAGE_SERV_USER}}
                  USE_VENV: "true"
                  ODOO_DB: ${{inputs.ODOO_DB}}
                  CICD_TOKEN: ${{secrets.CICD_TOKEN}}
